### ISSUE TITLE
Resizing shaders

### ISSUE THREAD

**Issue by DanielOaks** [vrld/shine#13]
Right now, if the screen is resized you need to recreate all the effects (otherwise they all have old canvases at the original size when they were inited).

Would it make sense to provide a function on effects that is called when the screen is resized? By default (if it doesn't exist) it would just call `self.canvas = love.graphics.newCanvas()`, but some effects have multiple canvases, and some would probably have to change other stuff, for more complex shaders (I have a planned chromatic aberration shader where this would apply, needs to do recalculations after screen size changes).

Alternatively, that could be overthinking it. Recreating the effects on resizing does work, and it's not something that happens often, so we might just want to recommend that and not worry about it?

**Comment by pyrareae** [comment]
Yes, this is a problem for my project as well, it would be good if it weren't as brittle about screen resizing. So, it looks like recreating the effects on resize is a workaround at least though it seems from your comment, which is good to know. Maybe someone should put that in the wiki :p

**Comment by DanielOaks** [comment]
Yeah, I threw this idea around but honestly I think just recreating the effects is the best thing to do. Most thing don't require resizing the window that much anyways (aside from switching from windowed/maximized/fullscreen, and I think a touch of possible graphical weirdness there is already not out of the ordinary). Wiki could be good, definitely.

**Comment by pablomayobre** [comment]
Resizing destroys canvases, and even Shaders since it creates a new OpenGL context, so recreating the effect is the best way to go.

**Comment by vrld** [comment]
I agree: this is easy to handle in the game (by [love.resize()](https://love2d.org/wiki/love.resize)), but hard to do on library side. Even more if you consider that the effect parameters need to be reset, too.
