### ISSUE TITLE
draw function should accept arguments!

### ISSUE THREAD

**Issue by josefnpat** [vrld/shine#14]
I'm really tired so maybe it does it already, but the docs only show that you can use draw with a function. I would like to be able to pass args in as well.

Perhaps something like;

`shine_effect:draw(funckyfunc,{1,2,3,4})`

**Comment by vrld** [comment]
Originally `draw()` is intented to be used like this:

```
effect:draw(function()
    draw()
    things()
    with()
    effect()
end)
draw_things_without_effect()
```

But I can see that forwarding arguments to the function (like pcall does) is useful.

Meanwhile, this works:

```
effect:draw(function() funckyfunc({1,2,3,4}) end)
```

**Comment by josefnpat** [comment]
neat, thanks!
