### ISSUE TITLE
0.10 Compatibility

### ISSUE THREAD

**Issue by JanWerder** [vrld/shine#16]
Is there chance of seeing that in the near future?

**Comment by vrld** [comment]
Sure. Which shaders are incompatible? You can also provide a pull request; partial fixed are also welcome!

**Comment by JanWerder** [comment]
I followed the instructions in the readme and it did throw me several errors, so I didn't get to the actual shaders to be honest. I believe the main library is incompatible

**Comment by vrld** [comment]
What did the error messages say?

**Comment by JanWerder** [comment]
The feature check at the start of the init script (https://github.com/vrld/shine/blob/master/init.lua#L105) is broken due to the the deprecated https://love2d.org/wiki/love.graphics.isSupported

**Comment by JanWerder** [comment]
I checked out your demo branch and it seems the errors are reproducable there

**Comment by vrld** [comment]
Thanks. I will have a look as soon as I have access to my computer (I am on mobile at the moment)

**Comment by JanWerder** [comment]
Nice, thanks!

**Comment by JanWerder** [comment]
Any luck yet? Do you require any further help? :)

**Comment by vrld** [comment]
Done. Let me know if some effects are still broken!

The demo is broken due to a regression in Quickie, but that will be fixed soon-ish.

**Comment by JanWerder** [comment]
Shine works perfectly
