### ISSUE TITLE
Move the source to a directory named `shine`

### ISSUE THREAD

**Issue by rxi** [vrld/shine#19]
I don't think it's immediately obvious that the user has to create a directory named `shine` containing the repo's source files, and that this is the thing that is being required in the usage examples.

Have you considered moving the source files to a directory named "shine" in the repository, or adding the instruction at the start of the usage text explaining that one has to create the directory of the specific name? I feel either of these would make it clearer for potential users, especially those unfamiliar with how `init.lua` files work with modules.

Thanks for the excellent library!

**Comment by vrld** [comment]
If you do a `git pull`, shine will land in its own directory. In any case, you're right in that the readme should contain a "Getting started" or "Install" section.
