### ISSUE TITLE
vignette has not any effect

### ISSUE THREAD

**Issue by lynx-seu** [vrld/shine#20]
under mac os x 10.11.5

**Comment by vrld** [comment]
Hard to reporduce with the given information. Have you tried changing the parameters?

**Comment by lynx-seu** [comment]
I found that it's ok in a Landscape.  However, it doesn't has any effect in a Portrait

**Comment by vrld** [comment]
Alright, I think I know what is going on: The vignette is computed using the aspect ratio `width / height`. In landscape, this is > 1 giving the expected result, but in portrait it does not. You can try to play around with the radius parameter (and maybe up the opacity) to see if that changes anything. In any case, I will update the shader to detect whether the format is landscape or portrait.

Good find!
