### ISSUE TITLE
callback is called, nothing shows on screen

### ISSUE THREAD

**Issue by andrascsibi** [vrld/shine#23]
I can't get any effects up and working. 

    -- somewhere during load (doesn't work with other effects either)
    shaders.flora = shine.colorgradesimple()
    shaders.flora.grade = {1.2,1.0,.6}

    -- somewhere in draw
    shaders.flora(function()
      print('bleep bloop')
      love.graphics.draw(flora, x, y-heightDelta, 0, TSCALE, TSCALE, 0, 0)
    end)

bleep bloop is printed endlessly, yet no `flora` appears on screen. The `love.graphics.draw` call is working all right if I move it outside the callback function.

OS: Mac OS X 10.11.2
Love version: 0.10.1

Am I doing something wrong?

**Comment by vrld** [comment]
Cannot reproduce because I dont own a Mac. :(
