### ISSUE TITLE
DMG shader seems to chop up the table length

### ISSUE THREAD

**Issue by josefnpat** [vrld/shine#26]
the dmg shader seems to ignore the fourth color unless there's five elements in the table:

```lua
local shine = require 'shine'
function love.load()
  cat = love.graphics.newImage("cat.jpg")
  effect = shine.dmg()
end
function love.draw()
  effect:draw(function()
    love.graphics.draw(cat)
  end)
end
```
![image](https://user-images.githubusercontent.com/646162/28687121-0bc5e4fc-72d3-11e7-942e-9fdaa9341e45.png)

Black is not one of the gameboy colors.

If I add an empty table to the default palette:
```lua
	{
		name = "default",
		colors = {
			{ 15/255, 56/255, 15/255},
			{ 48/255, 98/255, 48/255},
			{139/255,172/255, 15/255},
			{155/255,188/255, 15/255},{}
		}
	},
```

it works:

![image](https://user-images.githubusercontent.com/646162/28687164-2c7e32f8-72d3-11e7-8d49-cc1ebbf22b82.png)

Since I authored this module, I will look into this asap

**Comment by vrld** [comment]
I don't see any errors in the effect code. Could this be a bug in LÖVE?

**Comment by josefnpat** [comment]
I have this on my list of things to look into, but that list has grown so long at this point.

I'm not sure, but considering I added an extra `{}` at the end of it and that "fixed it", I'm thinking there's a very subtle bug in this lib or in this shader.

**Comment by davisdude** [comment]
Isn't this related to the issue mentioned [on the wiki page for Shader:send](https://love2d.org/wiki/Shader:send) and not a problem with the lib itself?

> There is a bug in version 0.10.2 which causes Shader:send to ignore the last argument when sending arrays. A simple workaround is to add an extra dummy argument when sending multiple values to a uniform array.

**Comment by vrld** [comment]
Alright, this workaround is already implemented (see [dmg.lua#L144](https://github.com/vrld/moonshine/blob/master/dmg.lua#L144)) – we can close this then.

**Comment by josefnpat** [comment]
@davisdude nice catch
