### ISSUE TITLE
Make an example/test

### ISSUE THREAD

**Issue by pablomayobre** [vrld/shine#3]
It would be nice to have a `.love` file to test this, something like changing between the shaders and so, so that you know how they look.

Also we could use some screenshots of this `.love` file to put in the wiki

**Comment by vrld** [comment]
I'll upload the demo from the [love forums](http://www.love2d.org/forums/viewtopic.php?f=5&t=79443) as separate branch.

Images for the wiki are planned and should be there soon(tm)
