### ISSUE TITLE
Why is using chromasep clears background to black color?

### ISSUE THREAD

**Issue by iddm** [vrld/shine#33]
Why is using chromasep clears background to black color? I wanted to add it to my chain but found that it clears the background and I can't reset it back to my color.

**Comment by vrld** [comment]
I am not sure I understand the problem. Can you give some example code where this issue happens?

**Comment by iddm** [comment]
This:

```lua
local moonshine = require("moonshine")
local effect = moonshine.chain(moonshine.effects.chromasep)

function love.load()
    love.graphics.setBackgroundColor(104, 136, 248)
end

function love.update(dt)
end
 
function love.draw()
    effect(function()
        love.graphics.circle("fill", 30, 30, 65)
    end)
end
```

results in clearing the background to the black color:

![Image](https://i.imgur.com/teRgB2T.png)

And without chromasep:

```lua
local moonshine = require("moonshine")
local effect = moonshine.chain(moonshine.effects.chromasep)

function love.load()
    love.graphics.setBackgroundColor(104, 136, 248)
end

function love.update(dt)
end
 
function love.draw()
    -- effect(function()
        love.graphics.circle("fill", 30, 30, 65)
    -- end)
end
```

![Image](https://i.imgur.com/Raj6iUN.png)

**Comment by vrld** [comment]
Should be fixed. Thanks for reporting!

**Comment by iddm** [comment]
@vrld thank you too for the response & fix :)
