### ISSUE TITLE
getting black screen with CRT

### ISSUE THREAD

**Issue by gustavostuff** [vrld/shine#35]
Maybe I'm mising something but I followed the instructions on the README. I'm using the CRT filter with the defaults values but I get a black CRT-shaped frame.

with the effect:
![with_effect](https://user-images.githubusercontent.com/10310223/34692573-da358da2-f47d-11e7-9691-b5ec9c8f693b.png)

with no effects:
![with_no_effect](https://user-images.githubusercontent.com/10310223/34692574-da506fc8-f47d-11e7-8fa3-eb448a0bd753.png)

game:
[mobile_version.zip](https://github.com/vrld/moonshine/files/1613056/mobile_version.zip)

**Comment by gustavostuff** [comment]
never mind, it looks it was just my fault, I unwrapped all the content of love.draw() and left only this:
`effectCRT(function()
        gr.draw(canvas, 0, 0, 0, sx, sy)
 end)
`

now it works

**Comment by pablomayobre** [comment]
@tavuntu you should close the issue
