### ISSUE TITLE
Add width and height parameter to moonshine.chain

### ISSUE THREAD

**Issue by MikuAuahDark** [vrld/shine#36]
By default moonshine calls `love.graphics.newCanvas()` where the canvas size is the window size. In some scenario, the target canvas size is larger than the window size and can result in clipping.

**Comment by pablomayobre** [comment]
There is also the issue of resizable windows, being able to expand to be bigger than the original screen size when the effect chain was created.

A good idea is to have a `chain.resize(w, h)` function that creates a `chain.buffer` function that replaces the `buffer` function defined in `init.lua`

I can PR this change if wanted, would look something like
```lua
chain.resize = function (w, h)
  local front, back = love.graphics.newCanvas(w, h), love.graphics.newCanvas(w, h)
  chain.buffer = function()
    back, front = front, back
    return front, back
  end
end

chain.resize()
```

And then in `chain.draw`:
```lua
for _,e in ipairs(chain) do
  (e.draw or moonshine.draw_shader)(chain.buffer, e.shader)
end
```
