### ISSUE TITLE
dynamically add/remove effects?

### ISSUE THREAD

**Issue by ghost** [vrld/shine#38]
If I wanted to use a single chain to create a sortof "stage", how could I dynamically enable or disable effects in the chain?

**Comment by taxilly** [comment]
You can use timers to modify the effect parameters, e.g.

```moon
  SPFX.effect = moonshine(moonshine.effects.chromasep).chain(moonshine.effects.glow)
  SPFX.effect.parameters = {
    chromasep: {angle: 0, radius: 0}
    glow: { strength: 0}
  }

  Timer.after 1, ->
    SPFX.effect.parameters.glow.strength = 10   
```
Ripped from my game but you get the gist of it.
