### ISSUE TITLE
Shader is applied to everything before effect(function()...

### ISSUE THREAD

**Issue by doble-d** [vrld/shine#40]
I'm doing it like in the example, I don't know what's wrong..

```lua
local moonshine = require 'moonshine'

function love.load(arg)
  effect = moonshine(moonshine.effects.filmgrain)
    .chain(moonshine.effects.vignette)
  effect.filmgrain.size = 2
end

function love.draw()
  -- Shouldn't be affected but it is
  love.graphics.rectangle("fill", 0,0, 200,200)
  
  effect(function()
    love.graphics.rectangle("fill", 300,200, 200,200)
  end)

  -- Not affected, it's fine
  love.graphics.rectangle("fill", 0,0, 200,200)
end
```

**Comment by pablomayobre** [comment]
Filmgrain draws a noise texture over the whole screen, vignette draws the borders over the whole screen... they are not applied to specific areas.

Please also note that moonshine is meant for post-processing effects so this is the expected behaviour

**Comment by vrld** [comment]
As Positive07 wrote: this is expected. See also the [readme](https://github.com/vrld/moonshine#drawing-effects):

> Everything that is drawn outside of `func(...)` will not be affected. For
example,
>
>```lua
>love.graphics.draw(img1, 0,0)
>chain.draw(function()
>  love.graphics.draw(img2, 200,0)
>end)
>love.graphics.draw(img3, 400,0)
>```
>
>will apply the effect to `img2`, but not to `img1` and `img3`. Note that some
>effects (like filmgrain) draw on the whole screen. So if in this example `chain`
>would consist of a gaussianblur and filmgrain effect, `img1` will be covered
>with grain, but will not be blurred, `img2` will get both effects, and `img3`
>will be left untouched.
