### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by konstantinkoeppe** [vrld/shine#43]
We would like to use this library in a project of ours. This library currently does not contain any licensing information. Could you maybe consider adding a license to clear things up?

**Comment by vrld** [comment]
License is MIT, see [here](https://github.com/vrld/moonshine/blob/master/init.lua#L1). Some effects (like [this](https://github.com/vrld/moonshine/blob/master/pixelate.lua)) are public domain. I will add a section to the README.
