### ISSUE TITLE
vignette

### ISSUE THREAD

**Issue by Spairkie** [vrld/shine#49]
vignette color didn't seem to work. I wanted to use a red color as a damage indicator for my game. Willing to help. Thanks

**Comment by flamendless** [comment]
How do you use it?

**Comment by Xella37** [comment]
> 
> 
> vignette color didn't seem to work. I wanted to use a red color as a damage indicator for my game. Willing to help. Thanks



> 
> 
> How do you use it?

It seems the color is in RGB with values from 0-255, instead of 0-1 with some of these. Try setting the value of the color like this:
`effect.vignette.color = {255, 0, 0}`
to have a red vignette.
