### ISSUE TITLE
Pixels have an offset in pixelated effect

### ISSUE THREAD

**Issue by gustavostuff** [vrld/shine#55]
So I'm doing a game that must censor some images (yeah, it's that kind of game) and I have to apply the pixelated effect to the image, but the pixels, no matter the size, always seem to be moved a half to the right and bottom, in other words, the pixel in 0, 0 is not really in 0, 0 (hopefully that makes sense). Here's what I mean:

![](https://i.postimg.cc/tCLgfqyk/Screen-Shot-2020-05-02-at-12-12-30-PM.png)

And what I need is this:

![](https://i.postimg.cc/R0mZSgWn/Screen-Shot-2020-05-02-at-12-13-04-PM.png)

I was able to workaround this by just changing ```pixelate.lua:28``` to:
```tc = floor(tc * scale + vec2(.0));```

**The issue with this** is that the whole filtered image is slightly moved respect to the actual image that is being processed. So my request here is to have a way to remove that 0.5 offset there and not affect the position of the whole processed output. I'm not really good with shaders, not at all.

Edit: I'm chaining gaussianblur there, that's why it's also blurry and not just pixelated. Just a note.

**Comment by gustavostuff** [comment]
using ```tc = floor(tc * scale + vec2(1.0));``` seems to fix the issue, not sure why 🤔

**Comment by vrld** [comment]
**wont fix**: moonshine assumes a pixel location like `(200, 100)` means that the pixel is centered at `x = 200, y = 100`. By default, love anchors images at the upper left corner. To fix your issue, center the images with the `ox, oy` parameters in [love.graphics.draw()](https://love2d.org/wiki/love.graphics.draw).

The line `tc = floor(tc * scale + vec2(0.5));` is responsible for centering the pixel as it effectively rounds the scaled texel coordinate to the nearest integer, e.g., `tc = (0.314, 0.271)`, `scale = (400, 300)` => `floor((0.314 * 400 + 0.5, .217 * 300 + 0.5)) = (126, 81)`.

With `tc = floor(tc * scale + 1.0)`, you always round to the next integer, which puts the pixel center in the upper left corner instead (but also shifts the pixel right and down). `tc = floor(tc * scale)` should have the same effect, without the shifting.

**Comment by tavuntu** [comment]
Thanks a lot. What effectively seems to fix my issue is ```tc = floor(tc * scale + 0.5);``` though.

**Comment by gustavostuff** [comment]
I see what you mean now but centering the image with ```ox, oy``` doesn't really make a difference (I tried it), the shader doesn't really "care" about how I'm drawing the image but about the final position, scale, etc. right? (even if I draw the image, by using ```ox, oy```, it will be just the same result, so the shader will process it in the same way).

**Comment by vrld** [comment]
Not the blurred image, the icons have to be centered.

**Comment by gustavostuff** [comment]
Ah, sorry, I didn't get it right, you meant to center the icons, I thought you mean the background image... I see what you mean now, but the icons are already centered, if you look closely to the first image, the pixels are the ones that have an offset.
